### ISSUE TITLE
Is multi symbol possible?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Tydude4Christ/Enums.NET#17]
```
enum NumericOperator
    {
        [Symbol("==","C#")]
        [Symbol("=","F#")]
        Equals,

        [Symbol("NotEquals")]
        [Symbol("!=","C#")]
        [Symbol("<>","F#")]
        NotEquals,

        [Symbol(">")]
        Greater,
    }
```

And I get can `==` by passing `C#`  key and `=` by passing `F#` key and `Equals` with no key from Equals enum value?

And I get can `>` by passing `C#` key or by `F#` key or no key from Greater enum value?

It may be used during serialization into several databases. E.g. same enum stored into SQL database and into search database and into analytics database.

**Comment by TylerBrinkley** [comment]
You can create a custom `EnumFormat` for each version you want using the `Enums.RegisterCustomEnumFormat` method but instead of calling `member.Attributes.Get<SymbolAttribute>` you can call `member.Attributes.GetAll<SymbolAttribute>` and filter the attribute by `C#`, `F#`, or none. Does that answer your question?

**Comment by TylerBrinkley** [comment]
Closing due to no response. Please re-open if your issue was not addressed.
